name: 'pokemon_dbt'
version: '1.0.0'
config-version: 2

profile: 'pokemon_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  pokemon_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table